package com.redhat.coolstore

rule "Total Shopping Cart Items"
    ruleflow-group "pricing-rules"
    no-loop true
    when
	$sc : ShoppingCart( )
	$sci : ShoppingCartItem( shoppingCart == $sc )
    then
	try {
		$sc.setCartItemTotal( $sc.getCartItemTotal() + ($sci.getPrice() * $sci.getQuantity()));
	} catch (Exception e) {
		System.out.println("Exception in first line.");
		throw e;
	}
	try {
		$sc.setCartItemPromoSavings($sc.getCartItemPromoSavings() + ($sci.getPromoSavings() * $sci.getQuantity()));
	} catch (Exception e) {
		System.out.println("Exception in second line.");
		throw e;
	}
	update( $sc );
	retract ($sci);
end
